db_file DEFAULT_DB_FILE = File.expand_path(
  './data/meeting_data.sqlite3',
  __dir__,
)
output File.expand_path('./team_slack_reports.md', __dir__)
image_dir File.expand_path('./images', __dir__)
teams [
  'Chef Client',
  'Chef Server',
  'Chef Workstation',
  'Automate',
  'Habitat',
  'Courier',
  'Inspec',
]
header <<~EOF
    # Chef Slack Meeting tracking
    This document tracks status updates from Progress teams. While other
    teams such as Sous Chefs, Cinc, and Meta sometimes post updates, this
    document tracks internal teams only

    This page is generated by slack_meeting_stats.rb, do not edit manually

    ## Trends

    [![Attendance](images/attendance-small.png)](images/attendance-full.png)
    [![Build Status
       Reports](images/build_status-small.png)](images/build_status-full.png)
EOF
