db_file DEFAULT_DB_FILE = File.expand_path(
  './data/meeting_data.sqlite3',
  __dir__,
)
output File.expand_path('./team_meeting_reports.md', __dir__)
image_dir File.expand_path('./images', __dir__)
teams []
header <<~EOF
    # Slack Meeting tracking

    This document trakcs our meetings!

    This page is generated by slack_meeting_stats.rb, do not edit manually

    ## Trends

    [![Attendance](images/attendance-small.png)](images/attendance-full.png)
    [![Build Status
       Reports](images/build_status-small.png)](images/build_status-full.png)
EOF
