require 'mixlib/config'
require_relative './log'

module OssStats
  module MeetingStatsConfig
    extend Mixlib::Config

    db_file File.expand_path('./data/meeting_data.sqlite3', Dir.pwd)
    dryrun false
    header <<~EOF
      # Meeting Stats

      This document tracks meeting attendance and participation.
      It was generated by slack_meeting_stats.rb, do not edit manually.

      ## Trends

      [![Attendance](images/attendance-small.png)](images/attendance-full.png)
      [![Build Status
         Reports](images/build_status-small.png)](images/build_status-full.png)

    EOF
    output File.expand_path('./meeting_stats.md', Dir.pwd)
    image_dir File.expand_path('./images', Dir.pwd)
    log_level :info
    mode 'record'
    teams []

    def self.config_file
      log.debug('config_file called')
      if OssStats::MeetingStatsConfig.config
        return OssStats::MeetingStatsConfig.config
      end

      [
        Dir.pwd,
        File.join(ENV['HOME'], '.config', 'oss_stats'),
        '/etc',
      ].each do |dir|
        f = File.join(dir, 'meeting_stats_config.rb')
        log.debug("Checking if #{f} exists...")
        return f if ::File.exist?(f)
      end

      nil
    end
  end
end
