name: Lint
on:
  push:
    branches: [main]
  pull_request:

jobs:
  ruby:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.3]
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get -y install imagemagick libmagickwand-dev
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run chefstyle
      run: ./scripts/run_chefstyle.sh
    - name: Run markdownlint
      run: ./scripts/run_markdownlint.sh
